// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/app/server/registry"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/hertz-contrib/registry/etcd"
	"log"
	"mini-douyin/internal/api_service"
	EtcdConfig "mini-douyin/pkg/etcd"
)

func main() {
	r, err := etcd.NewEtcdRegistry(EtcdConfig.Config.Etcd.EndPoints)
	if err != nil {
		log.Fatal(err)
	}

	h := server.Default(
		server.WithHostPorts(fmt.Sprintf("0.0.0.0:%d", api_service.Config.Port)),
		server.WithRegistry(r, &registry.Info{
			ServiceName: api_service.Config.ServerName,
			Addr:        utils.NewNetAddr("tcp", fmt.Sprintf("0.0.0.0:%d", api_service.Config.Port)),
			Weight:      10,
			Tags:        nil,
		}))

	register(h)
	h.Spin()
}
