// Code generated by hertz generator.

package main

import (
	"api.service/biz/redis"
	"api.service/biz/rpc"
	"api.service/biz/sentinel"
	"api.service/biz/vd"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	//rpc 服务初始化
	rpc.InitRPC()
	//sentinel 服务初始化
	sentinel.InitSentinel()
	//redis 初始化
	redis.InitRedis()
	//validate 初始化
	vd.InitVD()
	//log配置 初始化
	//log.InitLog()
}

func main() {
	Init()
	//监控
	h := server.Default(server.WithTracer(prometheus.NewServerTracer(":9091", "/hertz")))
	register(h)
	h.Spin()
}
