// Code generated by hertz generator.

package Core

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func rootMw() []app.HandlerFunc {
	// your code...
	hlog.Infof("")
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publish_ctionrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}
